### PR TITLE
Removes all references to ie_mob

### LINKED ISSUE #191: Generator fails when browserslist >= 4.8.4 installed
[Reduction](https://repl.it/repls/DefiantOpaqueEmulation)

---

When invoking `generateData()` with browserslist 4.8.4 or newer installed, the following error obtains:

```
TypeError: Cannot read property 'x' of undefined
    at generatePrefixMap (/home/runner/DefiantOpaqueEmulation/node_modules/inline-style-prefixer/lib/generator/generatePrefixMap.js:54:31)
    at generateData (/home/runner/DefiantOpaqueEmulation/node_modules/inline-style-prefixer/lib/generator/index.js:74:71)
    at /home/runner/DefiantOpaqueEmulation/index.js:6:30    at Script.runInContext (vm.js:133:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

I believe this is because `ie_mob` is hard-coded into the [`prefixBrowserMap`](https://github.com/robinweser/inline-style-prefixer/blob/211edd82854a9dbc97db179ade277c43f3f5a710/modules/generator/generatePrefixMap.js#L18) but as of browserslist 4.8.4 it is no longer returned by queries, presumably because it was marked as a dead browser in [this commit](https://github.com/browserslist/browserslist/commit/61e7c94a887fbd739c304f7ad2d7ba06bbba017e).

As a workaround, downgrading to browserslist 4.8.3 fixes the error.

### PR DESCRIPTION
**Pull request by outoftime**
`ie_mob` has been marked as a dead browser by `browserslist` and is thus no longer returned in `caniuse-api` queries when it depends on latest `browserslist`.

This pull request removes all references to `ie_mob` from the codebase and documentation.

Fixes #191

### CODE REVIEW

File: modules/__tests__/createPrefixer-test.js [hunk 1]
```diff
@@ -346,7 +345,6 @@ describe('Static Prefixer', () => {
       const input = { writingMode: 'horizontal-tb' }
       const output = {
         WebkitWritingMode: 'horizontal-tb',
-        msWritingMode: 'horizontal-tb',
```
Comment (outoftime) [inline modules/__tests__/createPrefixer-test.js]: According to `caniuse-api`, only `ie_mob` needed the `-ms-` vendor prefix:

```
> caniuse.getSupport('writing-mode')
{
  and_chr: { y: 66 },
  and_ff: { y: 57 },
  and_qq: { y: 1.2, x: 1.2 },
  and_uc: { y: 11.8 },
  android: { y: 3, x: 4.4, n: 2.3 },
  baidu: { y: 7.12 },
  chrome: { n: 6, u: 7, y: 8, x: 47 },
  edge: { y: 12 },
  firefox: { n: 40, y: 41 },
  ie: { a: 11 },
  ie_mob: { a: 11, x: 11 },
  ios_saf: { y: 5, x: 10.3, u: 4.2 },
  op_mini: {},
  op_mob: { n: 12.1, y: 37 },
  opera: { n: 12.1, y: 15, x: 34 },
  safari: { n: 4, u: 5, y: 5.1, x: 10.1 },
  samsung: { y: 4, x: 4 }
}
```

**Comment by outoftime** [comment]
Hey @robinweser is this good to merge?

**Comment by robinweser** [comment]
Yeah, I'm about to do that asap!
